# module import 에서 `Import "django.db" could not be resolved from source Pylance" ` 이런 오류 발생하면 해결 방법
- VSCODE에서 F1을 눌러서 Python 인터프리터 선택 - 나의 경우 글로벌로 바꾸니까 오류가 사라졌다.

# python manage.py makemigrations 명령어 사용 시 No changes detected
- django에서 이미 migration을 한 상태에서 다시 migration을 했을 경우에 발생한다. 즉, 연동된 db에서 변경된 부분이 없을 때 발생.
- settings.py의 INSTALLED_APPS에 들어가서 생성한 장고 프로젝트를 기입한다. (INSTALLED_APPS에 사전에 기입하지 않았을 경우)
- ![image](https://user-images.githubusercontent.com/69157076/175907605-a03e2081-6b9d-4491-8f32-80d8987edeba.png)
- 그 다음, djnago 명령어 makemigrations 뒤에 내가 생성한 앱의 이름을 기입한다.(여기서의 앱이란 작성한 프로젝트를 말한다)
- ![image](https://user-images.githubusercontent.com/69157076/175908032-42d2006d-a309-4df3-9bef-fc14cc3ace63.png)

